timeouts:
  refresh: 120
  create_project: 120
  install_per_repo: 300
  delete_per_repo: 60
  rename: 60
  git_remote: 5
  git_push: 120

create_project_repo_url: "https://github.com/israice/Create-Project-Folder.git"

base_directory: "NEW_PROJECTS"

cache:
  git_state_ttl_sec: 10

python:
  disable_bytecode: true

ui:
  default_push_message: "v0.0.2 - new table based dashboard"
